# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce08e96c8e9961e822e66ce5cc72ca161a13deb0bbf6ac069d516bba0968d93924ca3a940359c3cbcbcaa0d9a76df6cb87b367ea7bdeb369172a8952399f7583

test:
  secret_key_base: c7803a711b2305b94d327da548171aa97e6b5cc857791cac4a8f2ecbbfa7cfaf055a8a0f3b3ed7f29f55d2259a0a40705d43a60ea8bbd4f83b6991f635038f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
